### GET request to example server
POST {{baseurl}}/Webhook/start/{{workflowDefinitionId}}
Content-Type: application/json

{
    "initialData": "something old"
}

> {% client.global.set("workflowInstanceId", response.body) %}
###